tls_server_config:
  cert_file: "certs/node1.pem"
  key_file: "certs/node1-key.pem"
  client_ca_file: "certs/ca.pem"
  client_auth_type: "VerifyClientCertIfGiven"
tls_client_config:
  cert_file: "certs/node1.pem"
  key_file: "certs/node1-key.pem"
  ca_file: "certs/ca.pem"
